name: main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      max-parallel: 5
      matrix:
        os: ['ubuntu']
        python-version: ['3.8', '3.12']

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Install dependencies
        run: conda install --file ci/conda_requirements.txt 

      - name: Install CI packages
        run: conda install pycodestyle coverage

      - name: Install program
        run: pip install -e .

      - name: Check style
        run: pycodestyle .

      - name: Run unit tests
        run: coverage run -m unittest && coverage lcov

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
